/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

/**
 *
 * @author USER
 */
public class AdminPortalUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentPortalUI.class.getName());

    /**
     * Creates new form StudentPortalUI
     */
    public AdminPortalUI() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnStudentInfo = new javax.swing.JButton();
        btnPriorityHandling = new javax.swing.JButton();
        btnEnrollment = new javax.swing.JButton();
        btnEnrollmentHistory = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Portal");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Admin Portal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        btnStudentInfo.setBackground(new java.awt.Color(204, 255, 255));
        btnStudentInfo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnStudentInfo.setForeground(new java.awt.Color(51, 0, 153));
        btnStudentInfo.setText("Student Info");
        btnStudentInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        btnStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentInfoActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 330, 90));

        btnPriorityHandling.setBackground(new java.awt.Color(204, 255, 255));
        btnPriorityHandling.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnPriorityHandling.setForeground(new java.awt.Color(51, 0, 153));
        btnPriorityHandling.setText("Priority Handling");
        btnPriorityHandling.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        btnPriorityHandling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriorityHandlingActionPerformed(evt);
            }
        });
        jPanel1.add(btnPriorityHandling, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 330, 90));

        btnEnrollment.setBackground(new java.awt.Color(204, 255, 255));
        btnEnrollment.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnEnrollment.setForeground(new java.awt.Color(51, 0, 153));
        btnEnrollment.setText("Enrollment");
        btnEnrollment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        btnEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollmentActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 330, 90));

        btnEnrollmentHistory.setBackground(new java.awt.Color(204, 255, 255));
        btnEnrollmentHistory.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnEnrollmentHistory.setForeground(new java.awt.Color(51, 0, 153));
        btnEnrollmentHistory.setText("Enrollment History");
        btnEnrollmentHistory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        btnEnrollmentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollmentHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnrollmentHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 330, 90));

        btnLogOut.setBackground(new java.awt.Color(204, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(51, 0, 153));
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 670, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img13.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPriorityHandlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriorityHandlingActionPerformed
        // Click Priority Handling Button and go to Priority Handling Portal
        PriorityHandlingUI PHUI= new PriorityHandlingUI();
        PHUI.setVisible(true);
    }//GEN-LAST:event_btnPriorityHandlingActionPerformed

    private void btnStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentInfoActionPerformed
        // Click Log Out Button and go to Main UI
        DisplayStudentsUI DSUI= new DisplayStudentsUI();
        DSUI.setVisible(true);
    }//GEN-LAST:event_btnStudentInfoActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // Click Log Out Button and go to Main UI
        MainUI MUI= new MainUI();
        MUI.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollmentActionPerformed
        // Click Enrollment Button and go to Main UI
        EnrolledUI EUI= new EnrolledUI();
        EUI.setVisible(true);
    }//GEN-LAST:event_btnEnrollmentActionPerformed

    private void btnEnrollmentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollmentHistoryActionPerformed
        // Click Enrollment History Button and go to Main UI
        HistoryRetrievalUI HRUI= new HistoryRetrievalUI();
        HRUI.setVisible(true);
    }//GEN-LAST:event_btnEnrollmentHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentPortalUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnrollment;
    private javax.swing.JButton btnEnrollmentHistory;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPriorityHandling;
    private javax.swing.JButton btnStudentInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
