/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

/**
 *
 * @author USER
 */
public class DisplayStudentsUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DisplayStudentsUI.class.getName());

    /**
     * Creates new form DisplayStudentsUI
     */
    public DisplayStudentsUI() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSortedAplabetically = new javax.swing.JButton();
        btnFindStudents = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Display Students");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Display Students");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        btnSortedAplabetically.setBackground(new java.awt.Color(204, 255, 255));
        btnSortedAplabetically.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnSortedAplabetically.setForeground(new java.awt.Color(51, 0, 153));
        btnSortedAplabetically.setText("Sorted Alphabetically");
        btnSortedAplabetically.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        btnSortedAplabetically.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortedAplabeticallyActionPerformed(evt);
            }
        });
        jPanel1.add(btnSortedAplabetically, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 380, 100));

        btnFindStudents.setBackground(new java.awt.Color(204, 255, 255));
        btnFindStudents.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnFindStudents.setForeground(new java.awt.Color(51, 0, 153));
        btnFindStudents.setText("Find Students");
        btnFindStudents.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        btnFindStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindStudentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnFindStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 380, 100));

        btnExit.setBackground(new java.awt.Color(204, 255, 255));
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnExit.setForeground(new java.awt.Color(51, 0, 153));
        btnExit.setText("Exit");
        btnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 380, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img25.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TO Cancel Button Option
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFindStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindStudentsActionPerformed
        // Click Log Out Button and go to Main UI
        FindStudentsUI FSUI= new FindStudentsUI();
        FSUI.setVisible(true);
    }//GEN-LAST:event_btnFindStudentsActionPerformed

    private void btnSortedAplabeticallyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortedAplabeticallyActionPerformed
        // Click Log Out Button and go to Main UI
        AlphabeticallyUI FSUI= new AlphabeticallyUI();
        FSUI.setVisible(true);
    }//GEN-LAST:event_btnSortedAplabeticallyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DisplayStudentsUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFindStudents;
    private javax.swing.JButton btnSortedAplabetically;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
