/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

/**
 *
 * @author USER
 */
public class MainUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUI.class.getName());

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSystemManagement = new javax.swing.JButton();
        btnStudentPortal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DreamBridge");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("Bridging Your Dreams and Education...");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("DreamBridge");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 650, -1));

        btnSystemManagement.setBackground(new java.awt.Color(153, 204, 255));
        btnSystemManagement.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnSystemManagement.setForeground(new java.awt.Color(51, 0, 153));
        btnSystemManagement.setText("System Management");
        btnSystemManagement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        btnSystemManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemManagementActionPerformed(evt);
            }
        });
        jPanel1.add(btnSystemManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 400, 110));

        btnStudentPortal.setBackground(new java.awt.Color(153, 204, 255));
        btnStudentPortal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnStudentPortal.setForeground(new java.awt.Color(51, 0, 153));
        btnStudentPortal.setText("Student Portal");
        btnStudentPortal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true));
        btnStudentPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentPortalActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentPortal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 400, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1430, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentPortalActionPerformed
        // Sign In Button Option attrive at Studen Login portal
        StdLoginUI SLog= new StdLoginUI();
        SLog.setVisible(true);
    }//GEN-LAST:event_btnStudentPortalActionPerformed

    private void btnSystemManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemManagementActionPerformed
        // Sign In Button Option attrive at Admin Login portal
        AdminLoginUI ALog= new AdminLoginUI();
        ALog.setVisible(true);
    }//GEN-LAST:event_btnSystemManagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentPortal;
    private javax.swing.JButton btnSystemManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
