/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;
import Data.StudentFileDB;
import DataStructures.DoublyLinkedList;
import DataStructures.Link;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class StudentRegistrationUI extends javax.swing.JFrame {
    
    
    DoublyLinkedList list = new DoublyLinkedList();

    /**
     * Creates new form StudentRegistrationUI
     */
    public StudentRegistrationUI() {
        initComponents();
        setLocationRelativeTo(this);
        
        StudentFileDB.loadStudents(list);
    }
    
    private boolean checkVal(){
        
        if (txtStdID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Student ID cannot be blank");
            return false;
        }
        if (txtName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Name cannot be blank");
            return false;
        }
        if (txtAge.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Age cannot be blank");
            return false;
        }
        if (txtTimestamp.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enrollment Timestamp cannot be blank");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtStdID = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtTimestamp = new javax.swing.JTextField();
        rdoFresher = new javax.swing.JRadioButton();
        rdoSenior = new javax.swing.JRadioButton();
        rdoJunior = new javax.swing.JRadioButton();
        PatientCmdPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnRegistor = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SRTable = new javax.swing.JTable();
        cmbCourse = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Registration");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Student Registration ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Student ID ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 165, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 214, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Age");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 263, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Course enrolled  ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 312, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Student level ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 363, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText(" Timestamp");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 412, -1, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 211, 335, -1));

        txtStdID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStdIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtStdID, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 162, 335, -1));

        txtAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 260, 335, -1));

        txtTimestamp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTimestamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimestampActionPerformed(evt);
            }
        });
        jPanel1.add(txtTimestamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 409, 335, -1));

        rdoFresher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoFresher.setText("Senior");
        rdoFresher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoFresherActionPerformed(evt);
            }
        });
        jPanel1.add(rdoFresher, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 361, 98, -1));

        rdoSenior.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoSenior.setText("Fresher");
        rdoSenior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSeniorActionPerformed(evt);
            }
        });
        jPanel1.add(rdoSenior, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 361, 98, -1));

        rdoJunior.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoJunior.setText("Junior");
        jPanel1.add(rdoJunior, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 361, 98, -1));

        PatientCmdPanel.setBackground(new java.awt.Color(255, 255, 255));
        PatientCmdPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(51, 0, 153));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        PatientCmdPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 31, 150, -1));

        btnRegistor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistor.setForeground(new java.awt.Color(51, 0, 153));
        btnRegistor.setText("Registor");
        btnRegistor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistorActionPerformed(evt);
            }
        });
        PatientCmdPanel.add(btnRegistor, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 31, 150, -1));

        btnDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDisplay.setForeground(new java.awt.Color(51, 0, 153));
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        PatientCmdPanel.add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 31, 150, -1));

        jPanel1.add(PatientCmdPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 550, 70));

        SRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Age", "Course", "Level", "Timestamp"
            }
        ));
        jScrollPane1.setViewportView(SRTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 162, 741, 340));

        cmbCourse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Artificial Intelligence", "Machine Learning", "Cloud Computing", "Cyber Security", "Networking" }));
        cmbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourseActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 309, 335, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1381, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtTimestampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimestampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimestampActionPerformed

    private void txtStdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStdIDActionPerformed

    private void rdoSeniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSeniorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoSeniorActionPerformed

    private void rdoFresherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFresherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoFresherActionPerformed

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        //To Display Button Option
        DefaultTableModel model = (DefaultTableModel) SRTable.getModel();

        model.setRowCount(0);

        Link current = list.getFirst();

        while(current != null){

            model.addRow(new Object[]{
                current.studentId,
                current.name,
                current.age,
                current.courseEnrolled,
                current.level,
                current.timestamp
            });

            current = current.next;
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnRegistorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistorActionPerformed
        //To Registor Button Option
        if (checkVal()){

            try {
                String StudentID = txtStdID.getText();

                // Check Duplicate Student ID
                if (list.DuplicateStudentID(StudentID)) {
                    JOptionPane.showMessageDialog(this, "Student ID already exists!");
                    txtStdID.setText("");
                    txtName.setText("");
                    txtAge.setText("");
                    rdoSenior.setSelected(false);
                    rdoJunior.setSelected(false);
                    rdoFresher.setSelected(false);
                    txtTimestamp.setText("");
                    return;
                }

                String Name = txtName.getText();

                int Age;

                try {
                    Age = Integer.parseInt(txtAge.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid Age!");
                    return;
                }

                String Course = cmbCourse.getSelectedItem().toString();

                String Level="";
                if(rdoFresher.isSelected()) {
                    Level="Fresher";
                } else if (rdoJunior.isSelected()){
                    Level="Junior";
                } else if (rdoSenior.isSelected()) {
                    Level = "Senior";
                } else {
                    JOptionPane.showMessageDialog(this, "Please select Student Level");
                    return;
                }

                String Timestamp = txtTimestamp.getText();

                //Data insert at the end of DDL
                list.insertLast(StudentID, Name, Age, Course, Level, Timestamp);
                
                //Data save into the file
                StudentFileDB.saveStudent(StudentID, Name, Age, Course, Level, Timestamp);

                JOptionPane.showMessageDialog(this, "Data Inserted Successfully!");

                txtStdID.setText("");
                txtName.setText("");
                txtAge.setText("");
                cmbCourse.setSelectedIndex(-1);
                txtTimestamp.setText("");
                rdoSenior.setSelected(false);
                rdoJunior.setSelected(false);
                rdoFresher.setSelected(false);

            } catch (NumberFormatException e) {
                txtStdID.setText("");
                txtName.setText("");
                txtAge.setText("");
                cmbCourse.setSelectedIndex(-1);
                txtTimestamp.setText("");
                rdoSenior.setSelected(false);
                rdoJunior.setSelected(false);
                rdoFresher.setSelected(false);
            }
        }
    }//GEN-LAST:event_btnRegistorActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TO Exit Button Option
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistrationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PatientCmdPanel;
    private javax.swing.JTable SRTable;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegistor;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoFresher;
    private javax.swing.JRadioButton rdoJunior;
    private javax.swing.JRadioButton rdoSenior;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStdID;
    private javax.swing.JTextField txtTimestamp;
    // End of variables declaration//GEN-END:variables
}
